Project: RoR Forms
EroAuditore/re-former pull request #1
Opened 2021-03-24 16:50 UTC by chuckbuckethead

- Added User model with validations
- Added New and Edit views
- Used HTML forms, as well as `form_tag` and `form_with`
- UserController includes `new`, `create`, `edit`, and `update` methods
- `routes.rb` has a resource for `:users` with **only** the following actions `[:new, :create, :edit, :update]`

2021-03-24 23:53 UTC, oloomoses requested changes
## Changes required
Hello team, you have done a great job on this project :muscle: 
### Highlight
- Well done on  the linter and rubocop configuration :clap: 
- Well done on the pull request, it's simple and easy to follow :100:
### To improve
- [x] Kindly add a more detailed project description to the readme. Also, the setup instructions you have given are not for this project. Kindly fix that.
- [x] When I click on the username, I should be able to edit the user. Kindly add a link for editing an existing user.
- [x] for the commented out form and form_tag, it is recommended that you use `users_path`. The code should be like :point_down: 
```<form action="users_path" method="post" accept-charset="UTF-8">``` and
```<%= form_tag(users_path) do %>```

### Optional
- [x] It would be nice to use a partial for the form
- [ ] It would be nice to add some styling to the form to make it appealing

Kindly implement the above changes before submitting another review.

**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply**

_Slack: Oloo Moses_

2021-03-25 19:49 UTC, enaburekhan requested changes
# Status: Changes required:full_moon:
**Hi team!**
**Great job so far on this project:clap::clap:. Thank you for implementing the changes requested by the last reviewer. The `form` is working as expected:100:.**
However, we just need to make a few changes to get the project approved:muscle:.

**To improve**
- [x] As highlighted in the PR. Remove commented code from `edit action` in user_controller.rb. 
If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

**Optional**
- [x] Kindly fix all the comments below with `Optional` as a heading. It will make the project codebase more professional, clean, easy to read, and understand 

Make the required changes and when you are ready, request another review.
Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

2021-03-25 19:49 UTC, enaburekhan commented on app/controllers/users_controller.rb
> +    # @user.update(user_params)
It’s better to delete commented pieces of codes. If you need to review a previous version of your code, use git history

2021-03-25 19:49 UTC, enaburekhan commented on app/controllers/users_controller.rb
> +      redirect_to root_path
**Optional**
It should `redirect_to new_user_path` instead of the `root_path`

2021-03-25 19:49 UTC, enaburekhan commented on app/controllers/users_controller.rb
> +      redirect_to root_path
**Optional**
it should `redirect_to edit_user_path(<USER_ID>)`. You can change USER_ID to whatever code worked for you.

2021-03-25 19:49 UTC, enaburekhan commented on app/views/users/_form.html.erb
> +<% end %>
**Optional**
Move this logic to a helper. There should be absolutely no logic in the view. Views are used for displaying data that are passed to them from the controller and not for generating data.

2021-03-25 23:36 UTC, mke2111 approved these changes
# STATUS: APPROVED  🟡 🥇  

## Hey Happy Coders, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

2021-03-26 01:03 UTC, merged